### ISSUE TITLE
Add Ortholinear Keyboard Layout

### ISSUE THREAD

**Issue by Beethoven-n** [futo-org/futo-keyboard-layouts#1]
### Use Cases

I'm used to a mostly ortholinear layout from my last keyboard. It allowed me to gesture type words like "won't" without confusion for the word "wont," and so on. It's just nicer to have punctuation possible in gesture typing.
![AnySoftKeyboard English layout](https://github.com/user-attachments/assets/d7780faa-4c7e-439b-824b-819c69874a11)

### Proposal

Add an optional ortholinear button map to lay keys on.

**Comment by tenextractor** [comment]
In my opinion, this should be handled with the custom layout system instead of being added in the app.
Here is the YAML:
```
name: QWERTY Ortholinear
languages: en
rows:
  - letters: q w e r t y u i o p
  - letters: a s d f g h j k l '
  - letters: z x c v b n m
```
