### ISSUE TITLE
Issue with altPages and in Custom Layouts

### ISSUE THREAD

**Issue by Konstantinos-bkl** [futo-org/futo-keyboard-layouts#175]
Hello,

I’m encountering an issue while trying to use custom layouts in Futo Keyboard. I am trying to implement altPages in a custom layout YAML, but I'm getting the following error: 

Custom layout could not be loaded.

Cause: Expected a list, but got a map

I attempted to use the altPages to create a secondary layout for accented characters, but it does not seem to work as expected. I’ve attached a sample of the layout YAML I’m using:

name: Accented Toggle Keyboard

rows:
  - letters:
      - [q, q́]
      - [w, ẃ]
      - [e, é]
      - [r, ŕ]
      - [t, t́]
      - [y, ý]
      - [u, ú]
      - [i, í]
      - [o, ó]
      - [p, ṕ]
  - letters: a s d f g h j k l
  - letters: z x c v b n m
  - letters:
      - [🌐, alt]   # This key switches to alt page

altPages:
    rows:
      - letters: á ć ę ř ť ý ú í ó
      - letters: à ś đ ḟ ġ ħ ļ
      - letters: ž ẋ ç ḅ ñ ṃ
      - letters:
          - [⬅️, alt]  # Key to go back to main layout

          
Could you please confirm if support for altPages is expected in the current version or if there are any workarounds for switching between layouts using a key?

I am using Futo Keyboard v0.1.24.2 from the Play Store.

Thank you for your help!

**Comment by abb128** [comment]
Please see ipa.yaml for an example of this feature's syntax

Try the following:
```
name: Accented Toggle Keyboard
rows:
    - letters:
        - [q, q́]
        - [w, ẃ]
        - [e, é]
        - [r, ŕ]
        - [t, t́]
        - [y, ý]
        - [u, ú]
        - [i, í]
        - [o, ó]
        - [p, ṕ]
    - letters: a s d f g h j k l
    - letters: z x c v b n m
    - letters:
        - ["🌐|!code/key_to_alt_0_layout"]
altPages:
    -   - letters: á ć ę ř ť ý ú í ó
        - letters: à ś đ ḟ ġ ħ ļ
        - letters: ž ẋ ç ḅ ñ ṃ
        - letters:
            - ["⬅️|!code/key_to_alt_0_layout"]
  
```
